backend:
  name: git-gateway
  # name: test-repo # use this for testing
  branch: main

media_folder: src/static/img
public_folder: /img

site_url: https://staticform21.netlify.app
publish_mode: editorial_workflow

# logo_url: https://st.netlify.app/logo.svg

locale: en

collections:
  - label: Forms
    name: forms
    folder: src/forms
    preview_path: forms/{{slug}}
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Tanggal
        name: date
        widget: datetime
      - label: Nomor WhatsApp
        name: waNumber
        widget: string
      - label: Body text
        name: body
        widget: markdown
      - label: Form
        name: form
        widget: list
        types:
          - label: Text Field
            name: textfield
            widget: object
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Id, name: id, widget: string }
              - { label: Required, name: required, widget: boolean }
          - label: Select Field
            name: selectfield
            widget: object
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Id, name: id, widget: string }
              - { label: Required, name: required, widget: boolean }
              - label: Options
                name: enum
                widget: list
                field: { label: Option, name: option, widget: string }
  - label: Pages
    name: pages
    files:
      - label: Home
        name: Home
        file: src/index.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
  - label: Settings
    name: settings
    files:
      - label: Site Metadata
        name: metadata
        file: src/_data/site.json
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: URL, name: url, widget: string}
          - {label: Favicon, name: favicon, widget: image}