backend:
  # name: git-gateway
  name: test-repo ## only use this for local testing ###
  branch: main

media_folder: src/img
public_folder: /img

# uncomment to enable drafts
# publish_mode: editorial_workflow

# add your site url here without trailing "/" to enable
# preview link and local development with git-gateway
# site_url: 

collections:
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - label: Site Metadata # modify site.json
        name: metadata
        file: src/_data/site.json
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Description,
              name: description,
              widget: string,
              hint: 50-160 characters,
            }
          - { label: Image, name: image, widget: image }
          - { label: URL, name: url, widget: string }
          - { label: Favicon, name: favicon, widget: image }