# This file is Nunjucks / Jinja flavored YAML

##------------------------------ Main ------------------------------##

# Define backend to interact with.
# git-gateway: used in production, directly write to remote git
# test-repo: used for testing, doesn't show posts

backend:
  name: git-gateway
  branch: main

media_folder: src/img
public_folder: /img

# uncomment below to enable drafts
# publish_mode: editorial_workflow

site_url: "{{site.url|safe}}"

collections:
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - label: Site Metadata
        name: metadata
        file: src/_data/site.json
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: Description,
              name: description,
              widget: string,
              hint: 50-160 characters,
            }
          - { label: Image, name: image, widget: image }
          - { label: URL, name: url, widget: string }
          - { label: Favicon, name: favicon, widget: image }
          - { label: Show Hero, name: showHero, widget: boolean }
          - {
              label: Navigation,
              name: nav,
              widget: list,
              field:
                {
                  label: Link,
                  name: link,
                  widget: list,
                  max: 2,
                  hint: "example: GitHub, https://github.com",
                },
            }
