backend:
  name: "{{env.cmsBackend or 'git-gateway'}}"
  branch: "{{env.git.branch or 'main'}}"

media_folder: src/img
public_folder: /img
site_url: "{{site.url or env.deploy.url}}"

collections:
  - label: Settings
    name: settings
    files:
      - label: Site Metadata
        name: metadata
        file: src/_data/site.json
        editor:
          preview: false
        fields:
          - label: Title
            name: title
            widget: string
            hint: Title shown in navigation bar
          - label: Description
            name: description
            widget: string
            hint: Short description for SEO. 50-160 characters.
          - label: Image
            name: image
            widget: image
            hint: Image that will be shown in shared content
          - label: URL
            name: url
            widget: string
            pattern:
              - (^$|^https?://(?:.*/)?[^/.]+$)
              - valid url without trailing slash or empty
            hint: Your website url. Fill this to override detected url.
            default: "{{env.deploy.url}}"
            required: false
          - label: Favicon
            name: favicon
            widget: image
          - label: Navigation
            name: nav
            widget: list
            field:
              label: Link
              name: link
              widget: list
              max: 2
              hint: "example: GitHub, https://github.com"
            required: false
          - label: Themes
            name: themes
            widget: list
            hint: >-
              Curiousity kill the cat 🙀. Please read the documentation before
              adding / removing themes.
      - label: About
        name: about
        file: src/_data/about.json
        fields:
          - label: Repository URL
            name: repo
            widget: select
            options:
              - "{{env.git.url}}"
          - label: Branch
            name: branch
            widget: select
            options:
              - "{{env.git.branch}}"
